title: Penguin Dash
description: The Penguin Dash Static Server and it's small amount of documentation.
theme: just-the-docs

url: https://mimmeer-me.github.io/penguin_dash/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
